[project]
name = "cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.10.2",
    "reportlab>=4.4.10",
    "weasyprint>=68.1",
]
